const types = {
  ALL_PRODUCTS_SUCCESS: "ALL_PRODUCTS_SUCCESS",
  ATC_REQUEST: "ATC_REQUEST",
  ATC_SUCCESS: "ATC_SUCCESS",
  RFC_REQUEST: "RFC_REQUEST",
  RFC_SUCCESS: "RFC_SUCCESS",
  CHECKOUT_REQUEST: "CHECKOUT_REQUEST",
  CHECKOUT_SUCCESS: "CHECKOUT_SUCCESS",
  CHECKOUT_FAILURE: "CHECKOUT_FAILURE",
};

export default types;
